AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  music-backend

  Sample SAM Template for music-backend
  
Globals:
  Function:
    Timeout: 3

Resources:
  SongFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: songs/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        Songs:
          Type: Api 
          Properties:
            Path: /songs
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SongApi:
    Description: "API Gateway endpoint URL for Prod stage for songs api function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/songs/"
  SongFunction:
    Description: "SongLambda Function ARN"
    Value: !GetAtt SongFunction.Arn
  SongFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt SongFunctionRole.Arn
